spring:
  data:
    mongodb:
      database: game_accountant
      host: localhost
      port: 27017

game:
  cors:
    http:
      allowedOrigins: https://game-accountant.herokuapp.com/
      allowedMethods: PATCH, GET, POST, DELETE, OPTIONS, PUT