spring:
  data:
    mongodb:
      database: game_accountant

game:
  cors:
    http:
      allowedOrigins: https://game-accountant.herokuapp.com/
      allowedMethods: PATCH, GET, POST, DELETE, OPTIONS, PUT